import { createClient } from "@supabase/supabase-js";

const supabaseUrl="https://cggkruccjfhgxhqkjamk.supabase.co"
const supabaseAnonKey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnZ2tydWNjamZoZ3hocWtqYW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNTA4NjAsImV4cCI6MjA5MDYyNjg2MH0.nmcHZYQEbkb_gxyOGCRWUTonmObgJfrP29lHc_M-cEc"

export const supabase=createClient(supabaseUrl,supabaseAnonKey)